### ISSUE TITLE
Connection from go lang app

### ISSUE THREAD

**Issue by Natarajan77** [openlab-red/redis-ha#1]
Can you please tell us which Ip we should use to connect from go lang app also how does the url should look like? Thanks

**Comment by eye0fra** [comment]
Hi @Natarajan77,
You have to set the redis-sentinel service url on your [go redis client library](https://godoc.org/github.com/go-redis/redis)

```
$ oc get svc
NAME                     CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
backend-redis-master     172.30.163.243   <none>        6379/TCP    34s
backend-redis-sentinel   172.30.83.214    <none>        26379/TCP   34s

```

```
client := redis.NewFailoverClient(&redis.FailoverOptions{
    MasterName:    "mymaster",
    SentinelAddrs: []string{"backend-redis-sentinel:26379"},
})
client.Ping()
```

**Comment by Natarajan77** [comment]
In my case below is the setting. 
backend-redis 172.30.229.236 none    6379/TCP   app=backend-redis  7 days 
 backend-redis-master 172.30.68.10 none    6379/TCP   backend-redis-master=true  7 days 
 backend-redis-sentinel 172.30.167.20 none    26379/TCP   backend-redis-sentinel=true  7 days 

So from golang I should use below

client := redis.NewFailoverClient(&redis.FailoverOptions{
    MasterName:    "mymaster",
    SentinelAddrs: []string{"backend-redis-sentinel:26379"},
})
client.Ping()

and if master goes down and sentinel promotes one of the slave as master the connection string won't change?

**Comment by Natarajan77** [comment]
what this will return ? Will it return the master hostname or ip?

client := redis.NewFailoverClient(&redis.FailoverOptions{
    MasterName:    "mymaster",
    SentinelAddrs: []string{"backend-redis-sentinel:26379"},
})
client.Ping()

**Comment by eye0fra** [comment]
No the connection string won't change.
The sentinel is going to give you automatically the new master ip.
More info: [https://redis.io/topics/sentinel#obtaining-the-address-of-the-current-master](https://redis.io/topics/sentinel#obtaining-the-address-of-the-current-master)

**Comment by Natarajan77** [comment]
Thank you SIR for very prompt reply. God bless you.

**Comment by eye0fra** [comment]
You are welcome! 😄
