### ISSUE TITLE
sir one quick question

### ISSUE THREAD

**Issue by Natarajan77** [openlab-red/redis-ha#2]
when u deploy it I m seeing master and sentinel are bundled in one pod and for other each slave has its own pod and as well as same see for sentinel also it has its own pod.

What is the reasoning for one master and sentinel to bundle in one pod? Thanks

**Comment by eye0fra** [comment]
It's for the bootstrap process, once the cluster is up you can set the replicas to 0. 
The pod ( master and sentinel) uses the shared network namespace to bootstrap the Redis cluster.
In particular, the very first sentinel needs to know how to find the master.
The others subsequent sentinels will ask the first sentinel.

**Comment by Natarajan77** [comment]
Thank you again sir.
